import { createI18n } from 'vue-i18n'

export const LOCALE_STORAGE_KEY = 'anidog.locale'

export const localeOptions = [
  { value: 'zh-CN', label: '简体中文', shortLabel: '简' },
  { value: 'zh-TW', label: '繁體中文', shortLabel: '繁' },
  { value: 'ja-JP', label: '日本語', shortLabel: '日' },
  { value: 'en-US', label: 'English', shortLabel: 'EN' },
]

const messages = {
  'zh-CN': {
    common: {
      save: '保存',
      saveSettings: '保存设置',
      cancel: '取消',
      confirm: '确定',
      delete: '删除',
      edit: '编辑',
      reset: '重置',
      search: '搜索',
      loading: '加载中...',
      enabled: '已启用',
      disabled: '已禁用',
      enable: '启用',
      disable: '禁用',
      success: '成功',
      failed: '失败',
      unknown: '未知',
      current: '当前',
      language: '界面语言',
    },
    nav: {
      dashboard: '首页',
      anime: '我的追番',
      downloads: '下载管理',
      rss: 'RSS订阅',
      calendar: '放送日历',
      library: '番剧库',
      rules: '规则管理',
      search: '资源搜索',
      notifications: '通知设置',
      settings: '设置',
      searchPlaceholder: '搜索番剧...',
      switchLight: '切换到白天',
      switchDark: '切换到夜晚',
    },
    account: {
      user: '用户',
      admin: '🌟 管理员',
      resident: '居民',
      logout: '退出登录',
    },
    status: { pending: '等待中', downloading: '下载中', completed: '已完成', paused: '已暂停', failed: '已失败', queued: '队列中', superseded: '已替代' },
    auth: {
      welcome: '欢迎回来，继续追番之旅',
      username: '用户名',
      usernamePlaceholder: '请输入用户名',
      email: '邮箱',
      emailPlaceholder: '请输入邮箱地址',
      password: '密码',
      passwordPlaceholder: '请输入密码',
      passwordCreatePlaceholder: '请输入密码（至少6位）',
      confirmPassword: '确认密码',
      confirmPasswordPlaceholder: '请再次输入密码',
      remember: '记住我',
      login: '🐾 登录',
      loggingIn: '登录中...',
      noAccount: '还没有账户？',
      registerNow: '立即注册',
      loginSuccess: '登录成功，欢迎回来~',
      loginFailed: '登录失败，请检查用户名和密码',
      registerTitle: '注册新账号',
      registerSubtitle: '来岛上一起追番吧 🐾',
      createAccount: '✨ 创建账号',
      registering: '注册中...',
      hasAccount: '已有账号？',
      loginNow: '立即登录',
      passwordMismatch: '两次输入的密码不一致',
      registerSuccess: '注册成功，请登录~',
      registerFailed: '注册失败，请稍后重试',
    },
    settings: {
      title: '⚙️ 系统设置',
      subtitle: '配置您的番剧管理系统偏好设置',
      tabs: {
        download: '下载偏好', appearance: '外观主题', rename: '重命名设置',
        scheduler: '调度器', network: '网络代理', user: '用户设置', system: '系统信息',
      },
      languageTitle: '界面语言',
      languageDescription: '选择 AniDog 界面使用的语言，修改后立即生效。',
      skins: { grove: '🌿 动森（默认）', groveDescription: '米白沙地 + 草绿 + 暖橙，圆润饱满', classic: '常规', classicDescription: '中性灰 + 蓝紫，简洁克制' },
    },
    downloadPrefs: {
      activeSources: '主动下载源', activeSourcesDesc: '系统会按优先级主动为缺失集填补资源',
      stream: '🎬 流媒体源', streamDesc: '从 aafun/AGE 等流媒体站点抓取视频流（速度快，画质一般）', manageRules: '管理规则',
      bt: '🧲 BT 种子搜索', btDesc: '从公开 BT 站聚合搜索种子（画质高，速度取决于做种数）', enabledIndexers: '启用的 BT Indexer',
      downloadLimit: 'BT 下载限速（KB/s）', downloadLimitDesc: '0 表示不限速，保存后约 15 秒内生效', uploadLimit: 'BT 上传限速（KB/s）', uploadLimitDesc: '限制下载中和做种任务的总上传速度，0 表示不限速',
      rss: 'RSS 订阅（被动）', rssDesc: 'RSS 是按规则被动接收 feed 的独立通道，与主动下载互不干扰', rssEnable: '启用 RSS 定时刷新与规则下载', rssEnableDesc: '定时刷新已订阅的 Mikan 等 feed，命中规则即下载', manageFeeds: '管理 Feed',
      quality: '质量偏好', qualityDesc: '系统按这些偏好对所有候选打分，选出最佳匹配', resolution: '分辨率', preferredLanguages: '首选语言', minSize: '最小体积 (MB)', maxSize: '最大体积 (MB，0=不限)', groupWhitelist: '字幕组白名单', groupPlaceholder: '输入后回车添加', groupScore: '命中白名单的字幕组评分 +100，其他 -20',
      scheduler: '调度策略', schedulerDesc: '每隔一段时间自动检查所有追番的缺失集', sourcePriority: '主动源优先级（从上到下）', sourcePriorityDesc: '优先级决定搜索和竞速入队顺序；RSS 是被动通道，不参与此排序', checkInterval: '定时检查间隔（分钟）', checkIntervalDesc: '最小 5 分钟，建议 30 分钟',
      archive: '下载与归档', archiveDesc: '下载落盘目录、并发数与标准归档规则', downloadDir: '默认下载目录', downloadDirDesc: '所有来源的文件都按 <番剧名 (年份)>/Season NN 归档到此目录', concurrency: '并发下载数', concurrencyDesc: '同时进行的下载任务上限', minFree: '最少保留空间（GB）', minFreeDesc: '低于该空间时拒绝创建新下载', maxUsage: '最高使用率（%）', maxUsageDesc: '达到该比例时暂停新增下载', archiveImmediate: '完成即归档，无需定时扫描', archiveImmediateDesc: 'BT、RSS 和流媒体完成后统一命名为 标题 S01E01.ext，并原子移动到对应季度目录。',
      languages: { simplified: '简中', traditional: '繁中', japanese: '日文', english: '英文' }, sources: { bt: '🧲 普通 BT 聚合', mikan: '🍊 Mikan', stream: '🎬 流媒体' }, recommended: '推荐', saving: '保存中...', saved: '下载偏好已保存', saveFailed: '保存失败',
    },
    pages: {
      dashboard: { title: '仪表盘', subtitle: '番剧下载管理概览', refresh: '刷新', retry: '重试', animeCount: '番剧数量', rssCount: 'RSS 订阅', downloading: '正在下载', completed: '已完成', waitingCount: '等待 {count}', failedCount: '失败 {count}', recent7: '最近 7 天下载', statusDistribution: '状态分布', noDownloads: '暂无下载', noDownloadsDesc: '还没有任何下载记录哦~', recent: '最近下载', viewAll: '查看全部 →', name: '名称', source: '来源', size: '大小', status: '状态', updated: '更新时间', emptyTitle: '还没有下载记录', emptyDesc: '快去番剧库挑一部追起来吧', loadFailed: '加载数据失败', downloadCount: '下载数量' },
      calendar: { title: '📅 放送日历', subtitle: '查看当季番剧放送时间表', refreshing: '刷新中...', refresh: '刷新', today: '今天', itemCount: '{count}部', empty: '今天没有番剧放送', emptyDesc: '试试其他星期吧 🌸', fetchFailed: '获取放送日历失败', refreshed: '日历已刷新', refreshFailed: '刷新失败', subscribed: '追番成功', subscribeFailed: '追番失败', weekdays: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'] },
      animeList: { title: '🌸 我的追番', subtitle: '管理您的追番收藏', grid: '网格', list: '列表', searchShort: '搜索...', search: '搜索番剧...', status: '状态', sort: '排序', all: '全部', ongoing: '连载中', completed: '已完结', upcoming: '即将开播', dropped: '已弃番', recent: '最近更新', az: '首字母 A-Z', za: '首字母 Z-A', rating: '评分最高', empty: '暂无番剧', emptyDesc: '还没有追番哦~', add: '搜索添加', previous: '上一页', next: '下一页', page: '第 {page} 页 / 共 {total} 页', fetchFailed: '获取番剧列表失败', deleted: '已删除《{title}》', deleteFailed: '删除失败' },
      library: { filteredTitle: '🔍 筛选结果', trendingTitle: '🔥 热门番剧', filteredSubtitle: '多维发现番剧', trendingSubtitle: '来自 Bangumi 的实时热门趋势', search: '搜索番剧名...', loading: '加载中...', filter: '筛选', year: '年份', seasons: '季度（可多选）', sort: '排序', minRating: '最低评分', tags: '标签（点击切换）', reset: '🔄 重置筛选', count: '共 {count} 部', empty: '暂无匹配结果', emptyDesc: '试试调整一下筛选条件', previous: '上一页', next: '下一页', page: '第 {page} 页 / 共 {total} 页', unlimited: '不限', heat: '热度', rank: '排名', score: '评分', match: '匹配度', loadFailed: '加载失败', subscribed: '追番成功', subscribeFailed: '追番失败' },
      notFound: { title: '迷路啦~', description: '这只小狗找不到这一页啦，可能是去追番了 🌸', home: '返回首页', back: '返回上页' },
    },
  },
  'zh-TW': {
    common: {
      save: '儲存', saveSettings: '儲存設定', cancel: '取消', confirm: '確定', delete: '刪除', edit: '編輯', reset: '重設', search: '搜尋', loading: '載入中...', enabled: '已啟用', disabled: '已停用', enable: '啟用', disable: '停用', success: '成功', failed: '失敗', unknown: '未知', current: '目前', language: '介面語言',
    },
    nav: {
      dashboard: '首頁', anime: '我的追番', downloads: '下載管理', rss: 'RSS 訂閱', calendar: '播出日曆', library: '番劇庫', rules: '規則管理', search: '資源搜尋', notifications: '通知設定', settings: '設定', searchPlaceholder: '搜尋番劇...', switchLight: '切換到白天', switchDark: '切換到夜間',
    },
    account: { user: '使用者', admin: '🌟 管理員', resident: '居民', logout: '登出' },
    status: { pending: '等待中', downloading: '下載中', completed: '已完成', paused: '已暫停', failed: '已失敗', queued: '佇列中', superseded: '已取代' },
    auth: {
      welcome: '歡迎回來，繼續追番之旅', username: '使用者名稱', usernamePlaceholder: '請輸入使用者名稱', email: '電子郵件', emailPlaceholder: '請輸入電子郵件地址', password: '密碼', passwordPlaceholder: '請輸入密碼', passwordCreatePlaceholder: '請輸入密碼（至少 6 位）', confirmPassword: '確認密碼', confirmPasswordPlaceholder: '請再次輸入密碼', remember: '記住我', login: '🐾 登入', loggingIn: '登入中...', noAccount: '還沒有帳號？', registerNow: '立即註冊', loginSuccess: '登入成功，歡迎回來~', loginFailed: '登入失敗，請檢查使用者名稱和密碼', registerTitle: '註冊新帳號', registerSubtitle: '來島上一起追番吧 🐾', createAccount: '✨ 建立帳號', registering: '註冊中...', hasAccount: '已有帳號？', loginNow: '立即登入', passwordMismatch: '兩次輸入的密碼不一致', registerSuccess: '註冊成功，請登入~', registerFailed: '註冊失敗，請稍後再試',
    },
    settings: {
      title: '⚙️ 系統設定', subtitle: '設定您的番劇管理系統偏好',
      tabs: { download: '下載偏好', appearance: '外觀主題', rename: '重新命名設定', scheduler: '排程器', network: '網路代理', user: '使用者設定', system: '系統資訊' },
      languageTitle: '介面語言', languageDescription: '選擇 AniDog 介面使用的語言，變更後立即生效。',
      skins: { grove: '🌿 動森（預設）', groveDescription: '米白沙地 + 草綠 + 暖橙，圓潤飽滿', classic: '常規', classicDescription: '中性灰 + 藍紫，簡潔克制' },
    },
    downloadPrefs: {
      activeSources: '主動下載來源', activeSourcesDesc: '系統會按優先順序主動為缺失集補齊資源', stream: '🎬 串流媒體', streamDesc: '從 aafun/AGE 等串流網站擷取影片（速度快，畫質一般）', manageRules: '管理規則', bt: '🧲 BT 種子搜尋', btDesc: '從公開 BT 網站聚合搜尋種子（畫質高，速度取決於做種數）', enabledIndexers: '啟用的 BT Indexer', downloadLimit: 'BT 下載限速（KB/s）', downloadLimitDesc: '0 表示不限速，儲存後約 15 秒內生效', uploadLimit: 'BT 上傳限速（KB/s）', uploadLimitDesc: '限制下載與做種任務的總上傳速度，0 表示不限速', rss: 'RSS 訂閱（被動）', rssDesc: 'RSS 是按規則被動接收 feed 的獨立通道，與主動下載互不干擾', rssEnable: '啟用 RSS 定時更新與規則下載', rssEnableDesc: '定時更新已訂閱的 Mikan 等 feed，命中規則即下載', manageFeeds: '管理 Feed', quality: '品質偏好', qualityDesc: '系統按這些偏好為所有候選評分，選出最佳匹配', resolution: '解析度', preferredLanguages: '偏好語言', minSize: '最小容量 (MB)', maxSize: '最大容量 (MB，0=不限)', groupWhitelist: '字幕組白名單', groupPlaceholder: '輸入後按 Enter 新增', groupScore: '命中白名單的字幕組評分 +100，其他 -20', scheduler: '排程策略', schedulerDesc: '定時自動檢查所有追番的缺失集', sourcePriority: '主動來源優先順序（由上到下）', sourcePriorityDesc: '優先順序決定搜尋與競速入列順序；RSS 不參與此排序', checkInterval: '定時檢查間隔（分鐘）', checkIntervalDesc: '最少 5 分鐘，建議 30 分鐘', archive: '下載與歸檔', archiveDesc: '下載目錄、並行數與標準歸檔規則', downloadDir: '預設下載目錄', downloadDirDesc: '所有來源的檔案都按 <番劇名 (年份)>/Season NN 歸檔到此目錄', concurrency: '並行下載數', concurrencyDesc: '同時進行的下載任務上限', minFree: '最少保留空間（GB）', minFreeDesc: '低於該空間時拒絕新增下載', maxUsage: '最高使用率（%）', maxUsageDesc: '達到該比例時暫停新增下載', archiveImmediate: '完成即歸檔，無需定時掃描', archiveImmediateDesc: 'BT、RSS 和串流媒體完成後統一命名為 標題 S01E01.ext，並原子移動到對應季度目錄。', languages: { simplified: '簡中', traditional: '繁中', japanese: '日文', english: '英文' }, sources: { bt: '🧲 一般 BT 聚合', mikan: '🍊 Mikan', stream: '🎬 串流媒體' }, recommended: '建議', saving: '儲存中...', saved: '下載偏好已儲存', saveFailed: '儲存失敗',
    },
    pages: {
      dashboard: { title: '儀表板', subtitle: '番劇下載管理概覽', refresh: '更新', retry: '重試', animeCount: '番劇數量', rssCount: 'RSS 訂閱', downloading: '下載中', completed: '已完成', waitingCount: '等待 {count}', failedCount: '失敗 {count}', recent7: '最近 7 天下載', statusDistribution: '狀態分佈', noDownloads: '暫無下載', noDownloadsDesc: '還沒有任何下載紀錄~', recent: '最近下載', viewAll: '查看全部 →', name: '名稱', source: '來源', size: '大小', status: '狀態', updated: '更新時間', emptyTitle: '還沒有下載紀錄', emptyDesc: '快去番劇庫挑一部追起來吧', loadFailed: '載入資料失敗', downloadCount: '下載數量' },
      calendar: { title: '📅 播出日曆', subtitle: '查看當季番劇播出時間表', refreshing: '更新中...', refresh: '更新', today: '今天', itemCount: '{count} 部', empty: '今天沒有番劇播出', emptyDesc: '試試其他星期 🌸', fetchFailed: '取得播出日曆失敗', refreshed: '日曆已更新', refreshFailed: '更新失敗', subscribed: '追番成功', subscribeFailed: '追番失敗', weekdays: ['週日', '週一', '週二', '週三', '週四', '週五', '週六'] },
      animeList: { title: '🌸 我的追番', subtitle: '管理您的追番收藏', grid: '網格', list: '清單', searchShort: '搜尋...', search: '搜尋番劇...', status: '狀態', sort: '排序', all: '全部', ongoing: '連載中', completed: '已完結', upcoming: '即將開播', dropped: '已棄番', recent: '最近更新', az: '字首 A-Z', za: '字首 Z-A', rating: '評分最高', empty: '暫無番劇', emptyDesc: '還沒有追番~', add: '搜尋新增', previous: '上一頁', next: '下一頁', page: '第 {page} 頁 / 共 {total} 頁', fetchFailed: '取得番劇清單失敗', deleted: '已刪除《{title}》', deleteFailed: '刪除失敗' },
      library: { filteredTitle: '🔍 篩選結果', trendingTitle: '🔥 熱門番劇', filteredSubtitle: '多維發現番劇', trendingSubtitle: '來自 Bangumi 的即時熱門趨勢', search: '搜尋番劇名...', loading: '載入中...', filter: '篩選', year: '年份', seasons: '季度（可多選）', sort: '排序', minRating: '最低評分', tags: '標籤（點擊切換）', reset: '🔄 重設篩選', count: '共 {count} 部', empty: '暫無符合結果', emptyDesc: '請嘗試調整篩選條件', previous: '上一頁', next: '下一頁', page: '第 {page} 頁 / 共 {total} 頁', unlimited: '不限', heat: '熱度', rank: '排名', score: '評分', match: '匹配度', loadFailed: '載入失敗', subscribed: '追番成功', subscribeFailed: '追番失敗' },
      notFound: { title: '迷路啦~', description: '這隻小狗找不到這一頁，可能去追番了 🌸', home: '返回首頁', back: '返回上頁' },
    },
  },
  'ja-JP': {
    common: {
      save: '保存', saveSettings: '設定を保存', cancel: 'キャンセル', confirm: '確認', delete: '削除', edit: '編集', reset: 'リセット', search: '検索', loading: '読み込み中...', enabled: '有効', disabled: '無効', enable: '有効化', disable: '無効化', success: '成功', failed: '失敗', unknown: '不明', current: '選択中', language: '表示言語',
    },
    nav: {
      dashboard: 'ホーム', anime: 'マイアニメ', downloads: 'ダウンロード', rss: 'RSS 購読', calendar: '放送カレンダー', library: 'アニメライブラリ', rules: 'ルール管理', search: 'リソース検索', notifications: '通知設定', settings: '設定', searchPlaceholder: 'アニメを検索...', switchLight: 'ライトモードへ', switchDark: 'ダークモードへ',
    },
    account: { user: 'ユーザー', admin: '🌟 管理者', resident: 'ユーザー', logout: 'ログアウト' },
    status: { pending: '待機中', downloading: 'ダウンロード中', completed: '完了', paused: '一時停止', failed: '失敗', queued: 'キュー中', superseded: '代替済み' },
    auth: {
      welcome: 'おかえりなさい。アニメを楽しみましょう', username: 'ユーザー名', usernamePlaceholder: 'ユーザー名を入力', email: 'メールアドレス', emailPlaceholder: 'メールアドレスを入力', password: 'パスワード', passwordPlaceholder: 'パスワードを入力', passwordCreatePlaceholder: 'パスワードを入力（6文字以上）', confirmPassword: 'パスワード確認', confirmPasswordPlaceholder: 'パスワードを再入力', remember: 'ログイン状態を保持', login: '🐾 ログイン', loggingIn: 'ログイン中...', noAccount: 'アカウントをお持ちでないですか？', registerNow: '今すぐ登録', loginSuccess: 'ログインしました。おかえりなさい。', loginFailed: 'ログインに失敗しました。ユーザー名とパスワードを確認してください。', registerTitle: '新規アカウント登録', registerSubtitle: '一緒にアニメを楽しみましょう 🐾', createAccount: '✨ アカウント作成', registering: '登録中...', hasAccount: 'すでにアカウントをお持ちですか？', loginNow: 'ログイン', passwordMismatch: 'パスワードが一致しません。', registerSuccess: '登録しました。ログインしてください。', registerFailed: '登録に失敗しました。後でもう一度お試しください。',
    },
    settings: {
      title: '⚙️ システム設定', subtitle: 'アニメ管理システムの設定を変更します',
      tabs: { download: 'ダウンロード設定', appearance: 'テーマ', rename: 'ファイル名設定', scheduler: 'スケジューラー', network: 'ネットワークプロキシ', user: 'ユーザー設定', system: 'システム情報' },
      languageTitle: '表示言語', languageDescription: 'AniDog の表示言語を選択します。変更はすぐに反映されます。',
      skins: { grove: '🌿 どうぶつの森（既定）', groveDescription: 'アイボリー + グリーン + ウォームオレンジの丸みのあるテーマ', classic: 'クラシック', classicDescription: 'ニュートラルグレー + ブルーバイオレットのシンプルなテーマ' },
    },
    downloadPrefs: {
      activeSources: 'アクティブダウンロードソース', activeSourcesDesc: '優先順位に従って欠落エピソードを自動的に補完します', stream: '🎬 ストリーミング', streamDesc: 'aafun/AGE などから動画ストリームを取得（高速、標準画質）', manageRules: 'ルール管理', bt: '🧲 BT トレント検索', btDesc: '公開 BT サイトを横断検索（高画質、速度はシーダー数に依存）', enabledIndexers: '有効な BT Indexer', downloadLimit: 'BT ダウンロード制限（KB/s）', downloadLimitDesc: '0 は無制限。保存後約 15 秒で反映', uploadLimit: 'BT アップロード制限（KB/s）', uploadLimitDesc: 'ダウンロード中とシード中の合計速度。0 は無制限', rss: 'RSS 購読（パッシブ）', rssDesc: 'RSS はルールに従う独立したパッシブ経路です', rssEnable: 'RSS の定期更新とルールダウンロードを有効化', rssEnableDesc: 'Mikan などの購読 feed を定期更新し、ルール一致時にダウンロード', manageFeeds: 'Feed 管理', quality: '品質設定', qualityDesc: '候補を評価し、最適なリソースを選択します', resolution: '解像度', preferredLanguages: '優先言語', minSize: '最小サイズ (MB)', maxSize: '最大サイズ (MB、0=無制限)', groupWhitelist: '字幕グループホワイトリスト', groupPlaceholder: '入力後 Enter で追加', groupScore: 'ホワイトリスト一致は +100、その他は -20', scheduler: 'スケジュール戦略', schedulerDesc: 'すべてのアニメの欠落エピソードを定期的に確認', sourcePriority: 'ソース優先順位（上から下）', sourcePriorityDesc: '検索とレースキューの順序です。RSS はこの並び替えに含まれません', checkInterval: '確認間隔（分）', checkIntervalDesc: '最小 5 分、推奨 30 分', archive: 'ダウンロードと整理', archiveDesc: '保存先、並列数、標準アーカイブルール', downloadDir: '既定のダウンロード先', downloadDirDesc: 'すべてのファイルを <アニメ名 (年)>/Season NN 形式で保存', concurrency: '同時ダウンロード数', concurrencyDesc: '同時実行するダウンロード数の上限', minFree: '最小空き容量（GB）', minFreeDesc: 'これを下回ると新規ダウンロードを作成しません', maxUsage: '最大使用率（%）', maxUsageDesc: '到達時は新規ダウンロードを一時停止', archiveImmediate: '完了時に即時整理', archiveImmediateDesc: 'BT、RSS、ストリーミングを タイトル S01E01.ext に統一し、シーズンフォルダへ移動します。', languages: { simplified: '簡体字中国語', traditional: '繁体字中国語', japanese: '日本語', english: '英語' }, sources: { bt: '🧲 通常 BT 横断検索', mikan: '🍊 Mikan', stream: '🎬 ストリーミング' }, recommended: '推奨', saving: '保存中...', saved: 'ダウンロード設定を保存しました', saveFailed: '保存に失敗しました',
    },
    pages: {
      dashboard: { title: 'ダッシュボード', subtitle: 'アニメダウンロード管理の概要', refresh: '更新', retry: '再試行', animeCount: 'アニメ数', rssCount: 'RSS 購読', downloading: 'ダウンロード中', completed: '完了', waitingCount: '待機 {count}', failedCount: '失敗 {count}', recent7: '過去 7 日間のダウンロード', statusDistribution: 'ステータス分布', noDownloads: 'ダウンロードなし', noDownloadsDesc: 'ダウンロード履歴はまだありません', recent: '最近のダウンロード', viewAll: 'すべて表示 →', name: '名前', source: 'ソース', size: 'サイズ', status: '状態', updated: '更新日時', emptyTitle: 'ダウンロード履歴はありません', emptyDesc: 'ライブラリからアニメを選びましょう', loadFailed: 'データの読み込みに失敗しました', downloadCount: 'ダウンロード数' },
      calendar: { title: '📅 放送カレンダー', subtitle: '今シーズンのアニメ放送予定', refreshing: '更新中...', refresh: '更新', today: '今日', itemCount: '{count} 作品', empty: '今日の放送はありません', emptyDesc: '他の曜日を確認してください 🌸', fetchFailed: '放送カレンダーの取得に失敗しました', refreshed: 'カレンダーを更新しました', refreshFailed: '更新に失敗しました', subscribed: '追加しました', subscribeFailed: '追加に失敗しました', weekdays: ['日', '月', '火', '水', '木', '金', '土'] },
      animeList: { title: '🌸 マイアニメ', subtitle: '追跡中のアニメを管理', grid: 'グリッド', list: 'リスト', searchShort: '検索...', search: 'アニメを検索...', status: '状態', sort: '並び替え', all: 'すべて', ongoing: '放送中', completed: '完結', upcoming: '放送予定', dropped: '視聴中止', recent: '最近の更新', az: '名前 A-Z', za: '名前 Z-A', rating: '評価の高い順', empty: 'アニメなし', emptyDesc: '追跡中のアニメはありません', add: '検索して追加', previous: '前へ', next: '次へ', page: '{page} / {total} ページ', fetchFailed: 'アニメリストの取得に失敗しました', deleted: '『{title}』を削除しました', deleteFailed: '削除に失敗しました' },
      library: { filteredTitle: '🔍 絞り込み結果', trendingTitle: '🔥 人気アニメ', filteredSubtitle: '条件からアニメを発見', trendingSubtitle: 'Bangumi のリアルタイムトレンド', search: 'アニメ名を検索...', loading: '読み込み中...', filter: '絞り込み', year: '年', seasons: 'シーズン（複数選択可）', sort: '並び替え', minRating: '最低評価', tags: 'タグ（クリックで切替）', reset: '🔄 絞り込みをリセット', count: '{count} 作品', empty: '一致する結果なし', emptyDesc: '絞り込み条件を調整してください', previous: '前へ', next: '次へ', page: '{page} / {total} ページ', unlimited: '指定なし', heat: '人気', rank: 'ランク', score: '評価', match: '一致度', loadFailed: '読み込みに失敗しました', subscribed: '追加しました', subscribeFailed: '追加に失敗しました' },
      notFound: { title: '道に迷いました', description: 'このページは見つかりません。ワンちゃんはアニメを見に行ったようです 🌸', home: 'ホームへ', back: '前のページへ' },
    },
  },
  'en-US': {
    common: {
      save: 'Save', saveSettings: 'Save settings', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete', edit: 'Edit', reset: 'Reset', search: 'Search', loading: 'Loading...', enabled: 'Enabled', disabled: 'Disabled', enable: 'Enable', disable: 'Disable', success: 'Success', failed: 'Failed', unknown: 'Unknown', current: 'Current', language: 'Interface language',
    },
    nav: {
      dashboard: 'Home', anime: 'My anime', downloads: 'Downloads', rss: 'RSS subscriptions', calendar: 'Broadcast calendar', library: 'Anime library', rules: 'Rule management', search: 'Resource search', notifications: 'Notifications', settings: 'Settings', searchPlaceholder: 'Search anime...', switchLight: 'Switch to light mode', switchDark: 'Switch to dark mode',
    },
    account: { user: 'User', admin: '🌟 Administrator', resident: 'User', logout: 'Log out' },
    status: { pending: 'Waiting', downloading: 'Downloading', completed: 'Completed', paused: 'Paused', failed: 'Failed', queued: 'Queued', superseded: 'Superseded' },
    auth: {
      welcome: 'Welcome back. Continue your anime journey', username: 'Username', usernamePlaceholder: 'Enter your username', email: 'Email', emailPlaceholder: 'Enter your email address', password: 'Password', passwordPlaceholder: 'Enter your password', passwordCreatePlaceholder: 'Enter a password (at least 6 characters)', confirmPassword: 'Confirm password', confirmPasswordPlaceholder: 'Enter your password again', remember: 'Remember me', login: '🐾 Log in', loggingIn: 'Logging in...', noAccount: "Don't have an account?", registerNow: 'Register now', loginSuccess: 'Logged in. Welcome back!', loginFailed: 'Login failed. Check your username and password.', registerTitle: 'Create an account', registerSubtitle: 'Join us and enjoy anime together 🐾', createAccount: '✨ Create account', registering: 'Creating account...', hasAccount: 'Already have an account?', loginNow: 'Log in', passwordMismatch: 'The passwords do not match.', registerSuccess: 'Account created. Please log in.', registerFailed: 'Registration failed. Please try again later.',
    },
    settings: {
      title: '⚙️ System settings', subtitle: 'Configure your anime management preferences',
      tabs: { download: 'Download preferences', appearance: 'Appearance', rename: 'File naming', scheduler: 'Scheduler', network: 'Network proxy', user: 'User settings', system: 'System information' },
      languageTitle: 'Interface language', languageDescription: 'Choose the language used by AniDog. Changes take effect immediately.',
      skins: { grove: '🌿 Animal Crossing (default)', groveDescription: 'A rounded ivory, grass green, and warm orange theme', classic: 'Classic', classicDescription: 'A restrained neutral gray and blue-violet theme' },
    },
    downloadPrefs: {
      activeSources: 'Active download sources', activeSourcesDesc: 'Automatically find resources for missing episodes in priority order', stream: '🎬 Streaming source', streamDesc: 'Capture video streams from aafun, AGE, and similar sites (fast, average quality)', manageRules: 'Manage rules', bt: '🧲 BT torrent search', btDesc: 'Aggregate public BT sites (high quality; speed depends on seeders)', enabledIndexers: 'Enabled BT indexers', downloadLimit: 'BT download limit (KB/s)', downloadLimitDesc: '0 means unlimited. Changes apply in about 15 seconds.', uploadLimit: 'BT upload limit (KB/s)', uploadLimitDesc: 'Total upload speed for downloading and seeding tasks; 0 means unlimited', rss: 'RSS subscriptions (passive)', rssDesc: 'RSS is an independent passive channel driven by feed rules', rssEnable: 'Enable scheduled RSS refresh and rule downloads', rssEnableDesc: 'Refresh subscribed feeds such as Mikan and download matching entries', manageFeeds: 'Manage feeds', quality: 'Quality preferences', qualityDesc: 'Score all candidates using these preferences and select the best match', resolution: 'Resolution', preferredLanguages: 'Preferred languages', minSize: 'Minimum size (MB)', maxSize: 'Maximum size (MB, 0 = unlimited)', groupWhitelist: 'Subtitle group allowlist', groupPlaceholder: 'Type and press Enter', groupScore: 'Allowlisted groups score +100; others score -20', scheduler: 'Scheduling strategy', schedulerDesc: 'Periodically check all followed anime for missing episodes', sourcePriority: 'Active source priority (top to bottom)', sourcePriorityDesc: 'Priority controls search and race queue order. RSS is passive and does not participate.', checkInterval: 'Check interval (minutes)', checkIntervalDesc: 'Minimum 5 minutes; 30 minutes recommended', archive: 'Downloads and archiving', archiveDesc: 'Storage directory, concurrency, and standard archive rules', downloadDir: 'Default download directory', downloadDirDesc: 'Archive all files as <Anime title (year)>/Season NN under this directory', concurrency: 'Concurrent downloads', concurrencyDesc: 'Maximum number of active download tasks', minFree: 'Minimum free space (GB)', minFreeDesc: 'Reject new downloads below this amount of free space', maxUsage: 'Maximum usage (%)', maxUsageDesc: 'Pause new downloads when this percentage is reached', archiveImmediate: 'Archive immediately on completion', archiveImmediateDesc: 'Rename BT, RSS, and streaming files to Title S01E01.ext and atomically move them into the season directory.', languages: { simplified: 'Simplified Chinese', traditional: 'Traditional Chinese', japanese: 'Japanese', english: 'English' }, sources: { bt: '🧲 Standard BT aggregation', mikan: '🍊 Mikan', stream: '🎬 Streaming' }, recommended: 'recommended', saving: 'Saving...', saved: 'Download preferences saved', saveFailed: 'Failed to save',
    },
    pages: {
      dashboard: { title: 'Dashboard', subtitle: 'Anime download management overview', refresh: 'Refresh', retry: 'Retry', animeCount: 'Anime', rssCount: 'RSS subscriptions', downloading: 'Downloading', completed: 'Completed', waitingCount: '{count} waiting', failedCount: '{count} failed', recent7: 'Downloads in the last 7 days', statusDistribution: 'Status distribution', noDownloads: 'No downloads', noDownloadsDesc: 'There are no download records yet.', recent: 'Recent downloads', viewAll: 'View all →', name: 'Name', source: 'Source', size: 'Size', status: 'Status', updated: 'Updated', emptyTitle: 'No download records yet', emptyDesc: 'Choose an anime from the library to get started', loadFailed: 'Failed to load data', downloadCount: 'Download count' },
      calendar: { title: '📅 Broadcast calendar', subtitle: 'This season\'s anime broadcast schedule', refreshing: 'Refreshing...', refresh: 'Refresh', today: 'Today', itemCount: '{count} titles', empty: 'No anime airs today', emptyDesc: 'Try another day of the week 🌸', fetchFailed: 'Failed to load the broadcast calendar', refreshed: 'Calendar refreshed', refreshFailed: 'Refresh failed', subscribed: 'Anime followed', subscribeFailed: 'Failed to follow anime', weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] },
      animeList: { title: '🌸 My anime', subtitle: 'Manage your followed anime', grid: 'Grid', list: 'List', searchShort: 'Search...', search: 'Search anime...', status: 'Status', sort: 'Sort', all: 'All', ongoing: 'Ongoing', completed: 'Completed', upcoming: 'Upcoming', dropped: 'Dropped', recent: 'Recently updated', az: 'Title A-Z', za: 'Title Z-A', rating: 'Highest rated', empty: 'No anime', emptyDesc: 'You are not following any anime yet.', add: 'Search and add', previous: 'Previous', next: 'Next', page: 'Page {page} of {total}', fetchFailed: 'Failed to load anime list', deleted: 'Deleted {title}', deleteFailed: 'Delete failed' },
      library: { filteredTitle: '🔍 Filter results', trendingTitle: '🔥 Trending anime', filteredSubtitle: 'Discover anime with multiple filters', trendingSubtitle: 'Live trends from Bangumi', search: 'Search anime title...', loading: 'Loading...', filter: 'Filter', year: 'Year', seasons: 'Season (multiple)', sort: 'Sort', minRating: 'Minimum rating', tags: 'Tags (click to toggle)', reset: '🔄 Reset filters', count: '{count} titles', empty: 'No matching results', emptyDesc: 'Try adjusting the filters', previous: 'Previous', next: 'Next', page: 'Page {page} of {total}', unlimited: 'Any', heat: 'Popularity', rank: 'Rank', score: 'Rating', match: 'Relevance', loadFailed: 'Failed to load', subscribed: 'Anime followed', subscribeFailed: 'Failed to follow anime' },
      notFound: { title: 'Lost?', description: "This page couldn't be found. The puppy may have gone to watch anime 🌸", home: 'Back to home', back: 'Go back' },
    },
  },
}

const downloadMessages = {
  'zh-CN': { total: '共 {count} 个', checking: '检查中...', checkUpdates: '检查追番更新', add: '添加', search: '搜索...', selected: '已选 {count} 个', pause: '暂停', resume: '继续', delete: '删除', pauseAll: '全部暂停', resumeAll: '全部继续', all: '全部', downloading: '下载中', paused: '已暂停', completed: '已完成', failed: '失败', noMatch: '未找到匹配的任务', empty: '暂无下载任务', name: '名称', source: '源', size: '大小', speed: '速度', progress: '进度', time: '时间', actions: '操作', episode: '第 {episode} 集', completedAt: '完成于 {time}', createdAt: '创建于 {time}', retry: '重试', openLocation: '打开位置', addTitle: '添加下载', url: '下载链接', invalidUrl: '请输入有效的磁力链接或 URL', savePath: '保存路径', defaultPath: '留空使用默认下载目录', operationFailed: '操作失败', deleteTitle: '删除任务', deleteConfirm: '确定删除“{name}”？', deleteFailed: '删除失败', queued: '已加入队列', retryFailed: '重试失败', batchDelete: '批量删除', batchDeleteConfirm: '确定删除 {count} 个任务？', addFailed: '添加失败', desktopOnly: '本地打开功能需要桌面端支持', updateTriggered: '已触发全部追番更新检查', updateFailed: '检查更新失败', justNow: '刚刚', minutesAgo: '{count} 分钟前', hoursAgo: '{count} 小时前', daysAgo: '{count} 天前', stream: '流媒体', manual: '手动' },
  'zh-TW': { total: '共 {count} 個', checking: '檢查中...', checkUpdates: '檢查追番更新', add: '新增', search: '搜尋...', selected: '已選 {count} 個', pause: '暫停', resume: '繼續', delete: '刪除', pauseAll: '全部暫停', resumeAll: '全部繼續', all: '全部', downloading: '下載中', paused: '已暫停', completed: '已完成', failed: '失敗', noMatch: '找不到符合的任務', empty: '暫無下載任務', name: '名稱', source: '來源', size: '大小', speed: '速度', progress: '進度', time: '時間', actions: '操作', episode: '第 {episode} 集', completedAt: '完成於 {time}', createdAt: '建立於 {time}', retry: '重試', openLocation: '開啟位置', addTitle: '新增下載', url: '下載連結', invalidUrl: '請輸入有效的磁力連結或 URL', savePath: '儲存路徑', defaultPath: '留空使用預設下載目錄', operationFailed: '操作失敗', deleteTitle: '刪除任務', deleteConfirm: '確定刪除「{name}」？', deleteFailed: '刪除失敗', queued: '已加入佇列', retryFailed: '重試失敗', batchDelete: '批次刪除', batchDeleteConfirm: '確定刪除 {count} 個任務？', addFailed: '新增失敗', desktopOnly: '本機開啟功能需要桌面端支援', updateTriggered: '已觸發全部追番更新檢查', updateFailed: '檢查更新失敗', justNow: '剛剛', minutesAgo: '{count} 分鐘前', hoursAgo: '{count} 小時前', daysAgo: '{count} 天前', stream: '串流媒體', manual: '手動' },
  'ja-JP': { total: '合計 {count} 件', checking: '確認中...', checkUpdates: 'アニメの更新を確認', add: '追加', search: '検索...', selected: '{count} 件選択', pause: '一時停止', resume: '再開', delete: '削除', pauseAll: 'すべて一時停止', resumeAll: 'すべて再開', all: 'すべて', downloading: 'ダウンロード中', paused: '一時停止', completed: '完了', failed: '失敗', noMatch: '一致するタスクなし', empty: 'ダウンロードタスクなし', name: '名前', source: 'ソース', size: 'サイズ', speed: '速度', progress: '進捗', time: '時間', actions: '操作', episode: '第 {episode} 話', completedAt: '{time} に完了', createdAt: '{time} に作成', retry: '再試行', openLocation: '保存先を開く', addTitle: 'ダウンロード追加', url: 'ダウンロード URL', invalidUrl: '有効な Magnet リンクまたは URL を入力してください', savePath: '保存先', defaultPath: '空欄の場合は既定の保存先を使用', operationFailed: '操作に失敗しました', deleteTitle: 'タスクを削除', deleteConfirm: '「{name}」を削除しますか？', deleteFailed: '削除に失敗しました', queued: 'キューに追加しました', retryFailed: '再試行に失敗しました', batchDelete: '一括削除', batchDeleteConfirm: '{count} 件のタスクを削除しますか？', addFailed: '追加に失敗しました', desktopOnly: '保存先を開く機能はデスクトップ版が必要です', updateTriggered: 'すべての更新確認を開始しました', updateFailed: '更新確認に失敗しました', justNow: 'たった今', minutesAgo: '{count} 分前', hoursAgo: '{count} 時間前', daysAgo: '{count} 日前', stream: 'ストリーミング', manual: '手動' },
  'en-US': { total: '{count} total', checking: 'Checking...', checkUpdates: 'Check anime updates', add: 'Add', search: 'Search...', selected: '{count} selected', pause: 'Pause', resume: 'Resume', delete: 'Delete', pauseAll: 'Pause all', resumeAll: 'Resume all', all: 'All', downloading: 'Downloading', paused: 'Paused', completed: 'Completed', failed: 'Failed', noMatch: 'No matching tasks', empty: 'No download tasks', name: 'Name', source: 'Source', size: 'Size', speed: 'Speed', progress: 'Progress', time: 'Time', actions: 'Actions', episode: 'Episode {episode}', completedAt: 'Completed {time}', createdAt: 'Created {time}', retry: 'Retry', openLocation: 'Open location', addTitle: 'Add download', url: 'Download URL', invalidUrl: 'Enter a valid magnet link or URL', savePath: 'Save path', defaultPath: 'Leave blank to use the default download directory', operationFailed: 'Operation failed', deleteTitle: 'Delete task', deleteConfirm: 'Delete "{name}"?', deleteFailed: 'Delete failed', queued: 'Added to queue', retryFailed: 'Retry failed', batchDelete: 'Delete selected', batchDeleteConfirm: 'Delete {count} tasks?', addFailed: 'Failed to add', desktopOnly: 'Opening local folders requires the desktop app', updateTriggered: 'Started checking updates for all followed anime', updateFailed: 'Update check failed', justNow: 'Just now', minutesAgo: '{count} minutes ago', hoursAgo: '{count} hours ago', daysAgo: '{count} days ago', stream: 'Streaming', manual: 'Manual' },
}

for (const [locale, downloads] of Object.entries(downloadMessages)) {
  messages[locale].pages.downloads = downloads
}

const settingsDetailsMessages = {
  'zh-CN': { themeTitle: '主题皮肤', themeDesc: '切换整套视觉风格，选择后立即生效并记住偏好', current: '当前', themeNote: '切换皮肤只改变样式，不会影响下载、订阅和规则数据。', renameTitle: '文件归档命名', renameDesc: '下载完成时立即执行，不再依赖定时扫描任务', renameFormat: '标准格式：<番剧名 (年份)>/Season NN/番剧名 SnnEnn.ext。BT、RSS 与流媒体共用同一规则。', schedulerTitle: '后台调度', schedulerDesc: '配置定时任务和自动刷新', schedulerEnable: '启用调度器', proxyTitle: 'HTTP 代理', proxyDesc: '用于 Bangumi API、BT Indexer、Mikan、RSS 和通知等小型请求。qBittorrent 和 ffmpeg 的大流量数据仍由各自进程处理。', proxyAddress: '代理地址', proxyPlaceholder: '留空表示直连；Docker 部署建议 http://host.docker.internal:7890', proxyHint: '支持 http://、https:// 和 socks5://；容器内访问宿主机代理请使用 host.docker.internal。', testing: '测试中...', testConnection: '测试连接', connectionSuccess: '✓ 连接成功', connectionFailed: '✗ 连接失败', probeTarget: '探测目标：{target}', proxyHotUpdate: '保存后立即热更新，无需重启。系统会复用索引结果，避免重复请求。', accountTitle: '账户信息', accountDesc: '修改密码和个人信息', username: '用户名', oldPassword: '旧密码', newPassword: '新密码', confirmPassword: '确认新密码', oldPasswordPlaceholder: '请输入旧密码', newPasswordPlaceholder: '请输入新密码', confirmPasswordPlaceholder: '请再次输入新密码', changePassword: '修改密码', systemVersion: '系统版本', serviceUptime: '服务运行时间', unknown: '未知', hostUptime: '主机已开机 {time}', goHeap: 'Go 堆 {size} · GC {count} 次', cpuUsage: 'CPU 使用率', cores: '{count} 核', memoryUsage: '内存使用率', storageUsage: '媒体存储使用率', remaining: '剩余 {size}', dependencies: '依赖服务', connected: '已连接', disconnected: '未连接', connectionUsage: '连接 {used}/{open} 活跃', online: '在线', offline: '离线', autoRefresh: '每 {seconds} 秒自动刷新 · 最后更新 {time}', schedulerOn: '后台调度已启用', schedulerOff: '后台调度已停用', schedulerSaveFailed: '保存调度设置失败', proxySaved: '已保存并立即生效', saveFailed: '保存失败', enterOldPassword: '请输入旧密码', enterNewPassword: '请输入新密码', passwordMismatch: '两次输入的密码不一致', passwordChanged: '密码修改成功' },
  'zh-TW': { themeTitle: '主題外觀', themeDesc: '切換整套視覺風格，選擇後立即生效並記住偏好', current: '目前', themeNote: '切換外觀只改變樣式，不會影響下載、訂閱和規則資料。', renameTitle: '檔案歸檔命名', renameDesc: '下載完成時立即執行，不再依賴定時掃描', renameFormat: '標準格式：<番劇名 (年份)>/Season NN/番劇名 SnnEnn.ext。BT、RSS 與串流媒體共用同一規則。', schedulerTitle: '後台排程', schedulerDesc: '設定定時任務和自動更新', schedulerEnable: '啟用排程器', proxyTitle: 'HTTP 代理', proxyDesc: '用於 Bangumi API、BT Indexer、Mikan、RSS 和通知等小型請求。qBittorrent 與 ffmpeg 大流量由各自進程處理。', proxyAddress: '代理位址', proxyPlaceholder: '留空表示直連；Docker 建議 http://host.docker.internal:7890', proxyHint: '支援 http://、https:// 與 socks5://；容器內請使用 host.docker.internal。', testing: '測試中...', testConnection: '測試連線', connectionSuccess: '✓ 連線成功', connectionFailed: '✗ 連線失敗', probeTarget: '探測目標：{target}', proxyHotUpdate: '儲存後立即熱更新，無需重啟；系統會複用索引結果。', accountTitle: '帳戶資訊', accountDesc: '修改密碼和個人資訊', username: '使用者名稱', oldPassword: '舊密碼', newPassword: '新密碼', confirmPassword: '確認新密碼', oldPasswordPlaceholder: '請輸入舊密碼', newPasswordPlaceholder: '請輸入新密碼', confirmPasswordPlaceholder: '請再次輸入新密碼', changePassword: '修改密碼', systemVersion: '系統版本', serviceUptime: '服務運行時間', unknown: '未知', hostUptime: '主機已開機 {time}', goHeap: 'Go 堆積 {size} · GC {count} 次', cpuUsage: 'CPU 使用率', cores: '{count} 核心', memoryUsage: '記憶體使用率', storageUsage: '媒體儲存使用率', remaining: '剩餘 {size}', dependencies: '依賴服務', connected: '已連線', disconnected: '未連線', connectionUsage: '連線 {used}/{open} 使用中', online: '線上', offline: '離線', autoRefresh: '每 {seconds} 秒自動更新 · 最後更新 {time}', schedulerOn: '後台排程已啟用', schedulerOff: '後台排程已停用', schedulerSaveFailed: '儲存排程設定失敗', proxySaved: '已儲存並立即生效', saveFailed: '儲存失敗', enterOldPassword: '請輸入舊密碼', enterNewPassword: '請輸入新密碼', passwordMismatch: '兩次輸入的密碼不一致', passwordChanged: '密碼修改成功' },
  'ja-JP': { themeTitle: 'テーマ', themeDesc: '表示テーマを切り替えます。選択は保存されます。', current: '選択中', themeNote: 'テーマは外観のみを変更し、ダウンロードや購読データには影響しません。', renameTitle: 'ファイル整理名', renameDesc: 'ダウンロード完了時に即座に実行されます', renameFormat: '標準形式：<アニメ名 (年)>/Season NN/アニメ名 SnnEnn.ext。BT、RSS、ストリーミング共通です。', schedulerTitle: 'バックグラウンドスケジュール', schedulerDesc: '定期タスクと自動更新を設定', schedulerEnable: 'スケジューラーを有効化', proxyTitle: 'HTTP プロキシ', proxyDesc: 'Bangumi API、BT Indexer、Mikan、RSS、通知などの小規模リクエストに使用します。qBittorrent と ffmpeg の大容量データは各プロセスが処理します。', proxyAddress: 'プロキシアドレス', proxyPlaceholder: '空欄は直接接続。Docker では http://host.docker.internal:7890 を推奨', proxyHint: 'http://、https://、socks5:// に対応。コンテナからは host.docker.internal を使用します。', testing: 'テスト中...', testConnection: '接続テスト', connectionSuccess: '✓ 接続成功', connectionFailed: '✗ 接続失敗', probeTarget: '確認先: {target}', proxyHotUpdate: '保存後すぐに反映され、再起動は不要です。索引結果も再利用されます。', accountTitle: 'アカウント情報', accountDesc: 'パスワードと個人情報を変更', username: 'ユーザー名', oldPassword: '現在のパスワード', newPassword: '新しいパスワード', confirmPassword: '新しいパスワードの確認', oldPasswordPlaceholder: '現在のパスワードを入力', newPasswordPlaceholder: '新しいパスワードを入力', confirmPasswordPlaceholder: '新しいパスワードを再入力', changePassword: 'パスワード変更', systemVersion: 'システムバージョン', serviceUptime: 'サービス稼働時間', unknown: '不明', hostUptime: 'ホスト稼働 {time}', goHeap: 'Go ヒープ {size} · GC {count} 回', cpuUsage: 'CPU 使用率', cores: '{count} コア', memoryUsage: 'メモリ使用率', storageUsage: 'メディアストレージ使用率', remaining: '空き {size}', dependencies: '依存サービス', connected: '接続済み', disconnected: '未接続', connectionUsage: '接続 {used}/{open} 使用中', online: 'オンライン', offline: 'オフライン', autoRefresh: '{seconds} 秒ごとに自動更新 · 最終更新 {time}', schedulerOn: 'バックグラウンドスケジュールを有効にしました', schedulerOff: 'バックグラウンドスケジュールを停止しました', schedulerSaveFailed: 'スケジュール設定の保存に失敗しました', proxySaved: '保存して反映しました', saveFailed: '保存に失敗しました', enterOldPassword: '現在のパスワードを入力してください', enterNewPassword: '新しいパスワードを入力してください', passwordMismatch: 'パスワードが一致しません', passwordChanged: 'パスワードを変更しました' },
  'en-US': { themeTitle: 'Theme', themeDesc: 'Switch the visual style. Your selection takes effect immediately and is remembered.', current: 'Current', themeNote: 'Changing the theme only affects appearance; downloads, subscriptions, and rules are preserved.', renameTitle: 'Archive file naming', renameDesc: 'Applied immediately when a download completes; no scheduled scan is required', renameFormat: 'Standard format: <Anime title (year)>/Season NN/Anime title SnnEnn.ext. BT, RSS, and streaming use the same rule.', schedulerTitle: 'Background scheduler', schedulerDesc: 'Configure scheduled jobs and automatic refresh', schedulerEnable: 'Enable scheduler', proxyTitle: 'HTTP proxy', proxyDesc: 'Used for small requests such as Bangumi API, BT indexers, Mikan, RSS, and notifications. qBittorrent and ffmpeg handle their own high-volume traffic.', proxyAddress: 'Proxy address', proxyPlaceholder: 'Leave blank for direct connection; Docker recommendation: http://host.docker.internal:7890', proxyHint: 'Supports http://, https://, and socks5://. Use host.docker.internal from containers.', testing: 'Testing...', testConnection: 'Test connection', connectionSuccess: '✓ Connected', connectionFailed: '✗ Connection failed', probeTarget: 'Probe target: {target}', proxyHotUpdate: 'Changes apply immediately without a restart. Index results are reused to avoid duplicate requests.', accountTitle: 'Account information', accountDesc: 'Change your password and personal information', username: 'Username', oldPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password', oldPasswordPlaceholder: 'Enter your current password', newPasswordPlaceholder: 'Enter a new password', confirmPasswordPlaceholder: 'Enter the new password again', changePassword: 'Change password', systemVersion: 'System version', serviceUptime: 'Service uptime', unknown: 'Unknown', hostUptime: 'Host uptime {time}', goHeap: 'Go heap {size} · GC {count}', cpuUsage: 'CPU usage', cores: '{count} cores', memoryUsage: 'Memory usage', storageUsage: 'Media storage usage', remaining: '{size} remaining', dependencies: 'Dependent services', connected: 'Connected', disconnected: 'Disconnected', connectionUsage: '{used}/{open} connections active', online: 'Online', offline: 'Offline', autoRefresh: 'Refreshes every {seconds}s · Last updated {time}', schedulerOn: 'Background scheduler enabled', schedulerOff: 'Background scheduler disabled', schedulerSaveFailed: 'Failed to save scheduler settings', proxySaved: 'Saved and applied immediately', saveFailed: 'Save failed', enterOldPassword: 'Enter your current password', enterNewPassword: 'Enter a new password', passwordMismatch: 'The passwords do not match', passwordChanged: 'Password changed' },
}

for (const [locale, details] of Object.entries(settingsDetailsMessages)) {
  messages[locale].settings.details = details
}

const extraPageMessages = {
  'zh-CN': {
    search: { title: '🔍 资源搜索', subtitle: '跨站点搜索可下载的番剧资源', btTab: 'BT 资源', streamTab: '流媒体资源', btPlaceholder: '输入番剧名搜索 BT 资源...', sites: '站点：', batch: '合集', details: '查看详情 →', followDownload: '追番并下载', downloadOnly: '仅下载', notFound: '未找到相关资源', tryMore: '试试换个关键词，或选择更多站点', start: '开始搜索吧', startBtDesc: '输入番剧名，从 Mikan / DMHY / BangumiMoe 等站点查找资源', allRules: '所有规则', streamPlaceholder: '输入关键词搜索流媒体资源...', noRulesBefore: '还没有启用的流媒体规则。请先到', rulesLink: '流媒体规则', noRulesAfter: '添加并启用至少一个。', noStream: '未找到相关流媒体资源', startStreamDesc: '默认搜索所有启用的规则', enterKeyword: '请输入搜索关键词', selectSite: '至少选择一个站点', searchFailed: '搜索失败', streamSearchFailed: '流媒体搜索失败', missingUrl: '该候选缺少 magnet / torrent URL', queuedFollow: '已追番并加入下载队列', queuedUnmatched: '已加入下载队列（未匹配到番剧）', operationFailed: '操作失败', queued: '已加入下载队列', downloadFailed: '下载失败', noAnimeMatch: '没匹配到番剧条目，无法触发流媒体下载', streamSubscribed: '已追番，Orchestrator 会自动从该流媒体源下载', languages: { simplified: '简中', traditional: '繁中', japanese: '日文', english: '英文' } },
    notifications: { title: '🔔 通知设置', subtitle: '配置番剧更新通知渠道', addChannel: '添加渠道', testing: '测试中...', test: '测试', empty: '暂无通知渠道', emptyDesc: '点右上角添加一个通知渠道', editTitle: '编辑渠道', addTitle: '添加渠道', name: '渠道名称', namePlaceholder: '例如：我的 Telegram', type: '渠道类型', enable: '启用', deviceKeyPlaceholder: '你的设备 Key', sendKeyPlaceholder: '你的 SendKey', corpId: '企业 ID (corpid)', secret: '应用 Secret', secretPlaceholder: '应用的 Secret', agentId: '应用 AgentId', save: '保存', add: '添加', wecom: '企业微信', edit: '编辑', delete: '删除', loadFailed: '获取通知渠道失败', enterName: '请输入渠道名称', updated: '更新成功', added: '添加成功', testSuccess: '测试通知发送成功', testFailed: '测试失败', deleted: '已删除', deleteFailed: '删除失败' },
    rules: { title: '🌐 规则管理', subtitle: '管理番剧源解析规则（兼容 Kazumi 格式）', import: '导入', add: '添加规则', enabled: '启用', disabled: '禁用', edit: '编辑', test: '测试', delete: '删除', empty: '暂无规则', emptyDesc: '请添加或导入规则', editTitle: '编辑规则', addTitle: '添加规则', name: '规则名称 *', displayName: '显示名称', siteUrl: '站点 URL *', searchUrl: '搜索 URL *', keywordHint: '@keyword 会被替换为搜索词', searchListXpath: '搜索列表 XPath *', titleXpath: '标题 XPath *', linkXpath: '链接 XPath *', roadXpath: '线路 XPath', episodeXpath: '集数 XPath *', postSearch: 'POST 搜索', jsRender: '需要 JS 渲染', multiRoutes: '多线路', saving: '保存中...', save: '保存', importTitle: '📥 导入规则', importDesc: '上传 JSON 文件导入规则，兼容 Kazumi 规则格式', testTitle: '🧪 测试规则：{name}', testPlaceholder: '输入搜索关键词...', noResults: '无搜索结果', loadFailed: '获取规则失败', updated: '规则已更新', created: '规则已创建', saveFailed: '保存失败', deleteTitle: '删除规则', deleteConfirm: '确定删除规则“{name}”？', deleted: '已删除', deleteFailed: '删除失败', parseFailed: '响应解析失败', imported: '导入 {count} 条规则', importFailed: '导入失败', testFailed: '测试失败：{message}' },
    rss: { title: '📡 RSS 订阅管理', subtitle: '管理番剧 RSS 订阅源，自动追踪更新', add: '添加订阅源', total: '订阅源总数', active: '启用中', inactive: '已禁用', name: '名称', address: 'RSS 地址', status: '状态', parser: '解析器', filters: '过滤规则', lastUpdate: '最后更新', actions: '操作', empty: '暂无 RSS 订阅源', enabled: '启用', disabled: '禁用', ruleCount: '{count} 条规则', noRules: '无规则', never: '从未更新', view: '查看', refresh: '刷新', edit: '编辑', delete: '删除', addTitle: '添加 RSS 订阅源', feedName: '订阅源名称', feedNamePlaceholder: '例如：Mikanani', enableStatus: '启用状态', parserType: '解析器类型', filterRules: '过滤规则', filterPlaceholder: '输入后回车添加', testConnection: '测试连接', testing: '测试中...', testFeed: '测试 RSS 源', confirmAdd: '确认添加', itemsTitle: 'RSS 项目 - {name}', downloaded: '已下载', notDownloaded: '未下载', publishedAt: '发布时间：{time}', download: '下载', noItems: '暂无 RSS 项目', raw: '原始', loadFailed: '获取 RSS 源失败', invalidName: '请输入订阅源名称（至少 2 个字符）', invalidUrl: '请输入有效的 RSS 地址', added: '添加 RSS 源成功', addFailed: '添加 RSS 源失败', enterUrl: '请先输入 RSS 地址', testSuccess: '测试成功，获取到 {count} 个项目', testFailed: '测试失败：{message}', unknownError: '未知错误', itemsFailed: '获取 RSS 项目失败', refreshTriggered: '已触发刷新，稍后将出现在条目列表', refreshFailed: '刷新 RSS 源失败', editPending: '编辑功能待实现', deleted: '删除 RSS 源成功', deleteFailed: '删除 RSS 源失败', queued: '已添加到下载队列', queueFailed: '添加下载任务失败' },
  },
  'zh-TW': {
    search: { title: '🔍 資源搜尋', subtitle: '跨站點搜尋可下載的番劇資源', btTab: 'BT 資源', streamTab: '串流媒體資源', btPlaceholder: '輸入番劇名稱搜尋 BT 資源...', sites: '站點：', batch: '合集', details: '查看詳情 →', followDownload: '追番並下載', downloadOnly: '僅下載', notFound: '找不到相關資源', tryMore: '請更換關鍵字或選擇更多站點', start: '開始搜尋', startBtDesc: '輸入番劇名稱，從 Mikan / DMHY / BangumiMoe 等站點查找資源', allRules: '所有規則', streamPlaceholder: '輸入關鍵字搜尋串流媒體資源...', noRulesBefore: '尚未啟用串流媒體規則。請先到', rulesLink: '串流媒體規則', noRulesAfter: '新增並啟用至少一個。', noStream: '找不到相關串流媒體資源', startStreamDesc: '預設搜尋所有啟用的規則', enterKeyword: '請輸入搜尋關鍵字', selectSite: '至少選擇一個站點', searchFailed: '搜尋失敗', streamSearchFailed: '串流媒體搜尋失敗', missingUrl: '候選缺少 magnet / torrent URL', queuedFollow: '已追番並加入下載佇列', queuedUnmatched: '已加入下載佇列（未匹配到番劇）', operationFailed: '操作失敗', queued: '已加入下載佇列', downloadFailed: '下載失敗', noAnimeMatch: '未匹配到番劇項目，無法觸發串流媒體下載', streamSubscribed: '已追番，Orchestrator 將自動從此串流媒體來源下載', languages: { simplified: '簡中', traditional: '繁中', japanese: '日文', english: '英文' } },
    notifications: { title: '🔔 通知設定', subtitle: '設定番劇更新通知管道', addChannel: '新增管道', testing: '測試中...', test: '測試', empty: '暫無通知管道', emptyDesc: '點右上角新增通知管道', editTitle: '編輯管道', addTitle: '新增管道', name: '管道名稱', namePlaceholder: '例如：我的 Telegram', type: '管道類型', enable: '啟用', deviceKeyPlaceholder: '你的裝置 Key', sendKeyPlaceholder: '你的 SendKey', corpId: '企業 ID (corpid)', secret: '應用 Secret', secretPlaceholder: '應用的 Secret', agentId: '應用 AgentId', save: '儲存', add: '新增', wecom: '企業微信', edit: '編輯', delete: '刪除', loadFailed: '取得通知管道失敗', enterName: '請輸入管道名稱', updated: '更新成功', added: '新增成功', testSuccess: '測試通知傳送成功', testFailed: '測試失敗', deleted: '已刪除', deleteFailed: '刪除失敗' },
    rules: { title: '🌐 規則管理', subtitle: '管理番劇來源解析規則（相容 Kazumi 格式）', import: '匯入', add: '新增規則', enabled: '啟用', disabled: '停用', edit: '編輯', test: '測試', delete: '刪除', empty: '暫無規則', emptyDesc: '請新增或匯入規則', editTitle: '編輯規則', addTitle: '新增規則', name: '規則名稱 *', displayName: '顯示名稱', siteUrl: '站點 URL *', searchUrl: '搜尋 URL *', keywordHint: '@keyword 會替換為搜尋詞', searchListXpath: '搜尋清單 XPath *', titleXpath: '標題 XPath *', linkXpath: '連結 XPath *', roadXpath: '線路 XPath', episodeXpath: '集數 XPath *', postSearch: 'POST 搜尋', jsRender: '需要 JS 渲染', multiRoutes: '多線路', saving: '儲存中...', save: '儲存', importTitle: '📥 匯入規則', importDesc: '上傳 JSON 檔匯入規則，相容 Kazumi 格式', testTitle: '🧪 測試規則：{name}', testPlaceholder: '輸入搜尋關鍵字...', noResults: '無搜尋結果', loadFailed: '取得規則失敗', updated: '規則已更新', created: '規則已建立', saveFailed: '儲存失敗', deleteTitle: '刪除規則', deleteConfirm: '確定刪除規則「{name}」？', deleted: '已刪除', deleteFailed: '刪除失敗', parseFailed: '回應解析失敗', imported: '匯入 {count} 條規則', importFailed: '匯入失敗', testFailed: '測試失敗：{message}' },
    rss: { title: '📡 RSS 訂閱管理', subtitle: '管理番劇 RSS 訂閱來源，自動追蹤更新', add: '新增訂閱來源', total: '訂閱來源總數', active: '啟用中', inactive: '已停用', name: '名稱', address: 'RSS 位址', status: '狀態', parser: '解析器', filters: '過濾規則', lastUpdate: '最後更新', actions: '操作', empty: '暫無 RSS 訂閱來源', enabled: '啟用', disabled: '停用', ruleCount: '{count} 條規則', noRules: '無規則', never: '從未更新', view: '查看', refresh: '更新', edit: '編輯', delete: '刪除', addTitle: '新增 RSS 訂閱來源', feedName: '訂閱來源名稱', feedNamePlaceholder: '例如：Mikanani', enableStatus: '啟用狀態', parserType: '解析器類型', filterRules: '過濾規則', filterPlaceholder: '輸入後按 Enter 新增', testConnection: '測試連線', testing: '測試中...', testFeed: '測試 RSS 來源', confirmAdd: '確認新增', itemsTitle: 'RSS 項目 - {name}', downloaded: '已下載', notDownloaded: '未下載', publishedAt: '發布時間：{time}', download: '下載', noItems: '暫無 RSS 項目', raw: '原始', loadFailed: '取得 RSS 來源失敗', invalidName: '請輸入訂閱來源名稱（至少 2 個字元）', invalidUrl: '請輸入有效的 RSS 位址', added: '新增 RSS 來源成功', addFailed: '新增 RSS 來源失敗', enterUrl: '請先輸入 RSS 位址', testSuccess: '測試成功，取得 {count} 個項目', testFailed: '測試失敗：{message}', unknownError: '未知錯誤', itemsFailed: '取得 RSS 項目失敗', refreshTriggered: '已觸發更新，稍後會出現在項目清單', refreshFailed: '更新 RSS 來源失敗', editPending: '編輯功能尚未完成', deleted: '刪除 RSS 來源成功', deleteFailed: '刪除 RSS 來源失敗', queued: '已加入下載佇列', queueFailed: '新增下載任務失敗' },
  },
  'ja-JP': {
    search: { title: '🔍 リソース検索', subtitle: '複数サイトからダウンロード可能なアニメを検索', btTab: 'BT リソース', streamTab: 'ストリーミング', btPlaceholder: 'アニメ名で BT リソースを検索...', sites: 'サイト:', batch: '一括', details: '詳細を見る →', followDownload: 'フォローしてダウンロード', downloadOnly: 'ダウンロードのみ', notFound: 'リソースが見つかりません', tryMore: '別のキーワードやサイトをお試しください', start: '検索を始めましょう', startBtDesc: 'アニメ名を入力して Mikan / DMHY / BangumiMoe などを検索', allRules: 'すべてのルール', streamPlaceholder: 'ストリーミングを検索...', noRulesBefore: '有効なストリーミングルールがありません。', rulesLink: 'ストリーミングルール', noRulesAfter: 'で追加して有効にしてください。', noStream: 'ストリーミングリソースが見つかりません', startStreamDesc: '有効なルールをすべて検索します', enterKeyword: '検索キーワードを入力してください', selectSite: 'サイトを 1 つ以上選択してください', searchFailed: '検索に失敗しました', streamSearchFailed: 'ストリーミング検索に失敗しました', missingUrl: 'Magnet / torrent URL がありません', queuedFollow: 'フォローしてキューに追加しました', queuedUnmatched: 'キューに追加しました（アニメ未一致）', operationFailed: '操作に失敗しました', queued: 'キューに追加しました', downloadFailed: 'ダウンロードに失敗しました', noAnimeMatch: 'アニメが一致せず、ストリーミングを開始できません', streamSubscribed: 'フォローしました。Orchestrator がこのソースから自動ダウンロードします', languages: { simplified: '簡体字中国語', traditional: '繁体字中国語', japanese: '日本語', english: '英語' } },
    notifications: { title: '🔔 通知設定', subtitle: 'アニメ更新の通知先を設定', addChannel: '通知先を追加', testing: 'テスト中...', test: 'テスト', empty: '通知先がありません', emptyDesc: '右上から通知先を追加してください', editTitle: '通知先を編集', addTitle: '通知先を追加', name: '通知先名', namePlaceholder: '例: My Telegram', type: '種類', enable: '有効', deviceKeyPlaceholder: 'デバイス Key', sendKeyPlaceholder: 'SendKey', corpId: '企業 ID (corpid)', secret: 'アプリ Secret', secretPlaceholder: 'アプリの Secret', agentId: 'アプリ AgentId', save: '保存', add: '追加', wecom: 'WeCom', edit: '編集', delete: '削除', loadFailed: '通知先の取得に失敗しました', enterName: '通知先名を入力してください', updated: '更新しました', added: '追加しました', testSuccess: 'テスト通知を送信しました', testFailed: 'テストに失敗しました', deleted: '削除しました', deleteFailed: '削除に失敗しました' },
    rules: { title: '🌐 ルール管理', subtitle: 'アニメソース解析ルールを管理（Kazumi 互換）', import: 'インポート', add: 'ルール追加', enabled: '有効', disabled: '無効', edit: '編集', test: 'テスト', delete: '削除', empty: 'ルールがありません', emptyDesc: 'ルールを追加またはインポートしてください', editTitle: 'ルール編集', addTitle: 'ルール追加', name: 'ルール名 *', displayName: '表示名', siteUrl: 'サイト URL *', searchUrl: '検索 URL *', keywordHint: '@keyword は検索語に置換されます', searchListXpath: '検索一覧 XPath *', titleXpath: 'タイトル XPath *', linkXpath: 'リンク XPath *', roadXpath: 'ルート XPath', episodeXpath: 'エピソード XPath *', postSearch: 'POST 検索', jsRender: 'JS レンダリング', multiRoutes: '複数ルート', saving: '保存中...', save: '保存', importTitle: '📥 ルールをインポート', importDesc: 'Kazumi 互換の JSON ルールファイルをアップロード', testTitle: '🧪 ルールテスト: {name}', testPlaceholder: '検索キーワード...', noResults: '検索結果なし', loadFailed: 'ルールの取得に失敗しました', updated: 'ルールを更新しました', created: 'ルールを作成しました', saveFailed: '保存に失敗しました', deleteTitle: 'ルール削除', deleteConfirm: 'ルール「{name}」を削除しますか？', deleted: '削除しました', deleteFailed: '削除に失敗しました', parseFailed: 'レスポンス解析に失敗しました', imported: '{count} 件のルールをインポートしました', importFailed: 'インポートに失敗しました', testFailed: 'テスト失敗: {message}' },
    rss: { title: '📡 RSS 購読管理', subtitle: 'アニメ RSS フィードを管理して更新を自動追跡', add: 'フィード追加', total: 'フィード総数', active: '有効', inactive: '無効', name: '名前', address: 'RSS URL', status: '状態', parser: 'パーサー', filters: 'フィルター', lastUpdate: '最終更新', actions: '操作', empty: 'RSS フィードがありません', enabled: '有効', disabled: '無効', ruleCount: '{count} ルール', noRules: 'ルールなし', never: '未更新', view: '表示', refresh: '更新', edit: '編集', delete: '削除', addTitle: 'RSS フィード追加', feedName: 'フィード名', feedNamePlaceholder: '例: Mikanani', enableStatus: '有効状態', parserType: 'パーサー種別', filterRules: 'フィルタールール', filterPlaceholder: '入力して Enter で追加', testConnection: '接続テスト', testing: 'テスト中...', testFeed: 'RSS をテスト', confirmAdd: '追加', itemsTitle: 'RSS 項目 - {name}', downloaded: 'ダウンロード済み', notDownloaded: '未ダウンロード', publishedAt: '公開日時: {time}', download: 'ダウンロード', noItems: 'RSS 項目がありません', raw: 'Raw', loadFailed: 'RSS の取得に失敗しました', invalidName: 'フィード名を 2 文字以上で入力してください', invalidUrl: '有効な RSS URL を入力してください', added: 'RSS フィードを追加しました', addFailed: 'RSS フィードの追加に失敗しました', enterUrl: 'RSS URL を入力してください', testSuccess: 'テスト成功: {count} 項目', testFailed: 'テスト失敗: {message}', unknownError: '不明なエラー', itemsFailed: 'RSS 項目の取得に失敗しました', refreshTriggered: '更新を開始しました', refreshFailed: 'RSS の更新に失敗しました', editPending: '編集機能は準備中です', deleted: 'RSS フィードを削除しました', deleteFailed: 'RSS フィードの削除に失敗しました', queued: 'ダウンロードキューに追加しました', queueFailed: 'ダウンロードタスクの追加に失敗しました' },
  },
  'en-US': {
    search: { title: '🔍 Resource search', subtitle: 'Search downloadable anime across multiple sites', btTab: 'BT resources', streamTab: 'Streaming', btPlaceholder: 'Search BT resources by anime title...', sites: 'Sites:', batch: 'Batch', details: 'View details →', followDownload: 'Follow & download', downloadOnly: 'Download only', notFound: 'No matching resources', tryMore: 'Try another keyword or select more sites', start: 'Start searching', startBtDesc: 'Search Mikan, DMHY, BangumiMoe, and more by anime title', allRules: 'All rules', streamPlaceholder: 'Search streaming resources...', noRulesBefore: 'No streaming rules are enabled. Add and enable one under', rulesLink: 'Streaming rules', noRulesAfter: '.', noStream: 'No matching streaming resources', startStreamDesc: 'All enabled rules are searched by default', enterKeyword: 'Enter a search keyword', selectSite: 'Select at least one site', searchFailed: 'Search failed', streamSearchFailed: 'Streaming search failed', missingUrl: 'This candidate has no magnet / torrent URL', queuedFollow: 'Followed and added to the download queue', queuedUnmatched: 'Added to queue (no matching anime)', operationFailed: 'Operation failed', queued: 'Added to the download queue', downloadFailed: 'Download failed', noAnimeMatch: 'No anime match; streaming download cannot be started', streamSubscribed: 'Followed. Orchestrator will download from this streaming source automatically.', languages: { simplified: 'Simplified Chinese', traditional: 'Traditional Chinese', japanese: 'Japanese', english: 'English' } },
    notifications: { title: '🔔 Notification settings', subtitle: 'Configure anime update notification channels', addChannel: 'Add channel', testing: 'Testing...', test: 'Test', empty: 'No notification channels', emptyDesc: 'Add a notification channel from the top right', editTitle: 'Edit channel', addTitle: 'Add channel', name: 'Channel name', namePlaceholder: 'For example: My Telegram', type: 'Channel type', enable: 'Enable', deviceKeyPlaceholder: 'Your device key', sendKeyPlaceholder: 'Your SendKey', corpId: 'Company ID (corpid)', secret: 'App secret', secretPlaceholder: 'App secret', agentId: 'App AgentId', save: 'Save', add: 'Add', wecom: 'WeCom', edit: 'Edit', delete: 'Delete', loadFailed: 'Failed to load notification channels', enterName: 'Enter a channel name', updated: 'Updated', added: 'Added', testSuccess: 'Test notification sent', testFailed: 'Test failed', deleted: 'Deleted', deleteFailed: 'Delete failed' },
    rules: { title: '🌐 Rule management', subtitle: 'Manage anime source parsing rules (Kazumi compatible)', import: 'Import', add: 'Add rule', enabled: 'Enabled', disabled: 'Disabled', edit: 'Edit', test: 'Test', delete: 'Delete', empty: 'No rules', emptyDesc: 'Add or import a rule', editTitle: 'Edit rule', addTitle: 'Add rule', name: 'Rule name *', displayName: 'Display name', siteUrl: 'Site URL *', searchUrl: 'Search URL *', keywordHint: '@keyword is replaced with the search term', searchListXpath: 'Search list XPath *', titleXpath: 'Title XPath *', linkXpath: 'Link XPath *', roadXpath: 'Route XPath', episodeXpath: 'Episode XPath *', postSearch: 'POST search', jsRender: 'Requires JS rendering', multiRoutes: 'Multiple routes', saving: 'Saving...', save: 'Save', importTitle: '📥 Import rules', importDesc: 'Upload a Kazumi-compatible JSON rule file', testTitle: '🧪 Test rule: {name}', testPlaceholder: 'Enter a search keyword...', noResults: 'No search results', loadFailed: 'Failed to load rules', updated: 'Rule updated', created: 'Rule created', saveFailed: 'Save failed', deleteTitle: 'Delete rule', deleteConfirm: 'Delete rule "{name}"?', deleted: 'Deleted', deleteFailed: 'Delete failed', parseFailed: 'Failed to parse response', imported: 'Imported {count} rules', importFailed: 'Import failed', testFailed: 'Test failed: {message}' },
    rss: { title: '📡 RSS subscriptions', subtitle: 'Manage anime RSS feeds and track updates automatically', add: 'Add feed', total: 'Total feeds', active: 'Enabled', inactive: 'Disabled', name: 'Name', address: 'RSS URL', status: 'Status', parser: 'Parser', filters: 'Filter rules', lastUpdate: 'Last update', actions: 'Actions', empty: 'No RSS feeds', enabled: 'Enabled', disabled: 'Disabled', ruleCount: '{count} rules', noRules: 'No rules', never: 'Never', view: 'View', refresh: 'Refresh', edit: 'Edit', delete: 'Delete', addTitle: 'Add RSS feed', feedName: 'Feed name', feedNamePlaceholder: 'For example: Mikanani', enableStatus: 'Enabled', parserType: 'Parser type', filterRules: 'Filter rules', filterPlaceholder: 'Type and press Enter', testConnection: 'Test connection', testing: 'Testing...', testFeed: 'Test RSS feed', confirmAdd: 'Add feed', itemsTitle: 'RSS items - {name}', downloaded: 'Downloaded', notDownloaded: 'Not downloaded', publishedAt: 'Published: {time}', download: 'Download', noItems: 'No RSS items', raw: 'Raw', loadFailed: 'Failed to load RSS feeds', invalidName: 'Enter a feed name with at least 2 characters', invalidUrl: 'Enter a valid RSS URL', added: 'RSS feed added', addFailed: 'Failed to add RSS feed', enterUrl: 'Enter an RSS URL first', testSuccess: 'Test succeeded: {count} items', testFailed: 'Test failed: {message}', unknownError: 'Unknown error', itemsFailed: 'Failed to load RSS items', refreshTriggered: 'Refresh started; items will appear shortly', refreshFailed: 'Failed to refresh RSS feed', editPending: 'Editing is not implemented yet', deleted: 'RSS feed deleted', deleteFailed: 'Failed to delete RSS feed', queued: 'Added to download queue', queueFailed: 'Failed to add download task' },
  },
}

for (const [locale, pages] of Object.entries(extraPageMessages)) {
  Object.assign(messages[locale].pages, pages)
}

const extraCommonMessages = {
  'zh-CN': { browse: '浏览：', emptyDirectory: '空目录', savedDirectoryMissing: '已保存的目录不存在，当前已回到下载根目录', readDirectoryFailed: '读取目录失败', noOptions: '无选项', select: '请选择', close: '关闭', progress: '进度', empty: '暂无内容' },
  'zh-TW': { browse: '瀏覽：', emptyDirectory: '空目錄', savedDirectoryMissing: '已儲存的目錄不存在，目前已回到下載根目錄', readDirectoryFailed: '讀取目錄失敗', noOptions: '無選項', select: '請選擇', close: '關閉', progress: '進度', empty: '暫無內容' },
  'ja-JP': { browse: '参照:', emptyDirectory: '空のフォルダー', savedDirectoryMissing: '保存先が存在しないため、ダウンロードのルートに戻りました', readDirectoryFailed: 'フォルダーの読み込みに失敗しました', noOptions: '選択肢なし', select: '選択してください', close: '閉じる', progress: '進捗', empty: '項目がありません' },
  'en-US': { browse: 'Browse:', emptyDirectory: 'Empty directory', savedDirectoryMissing: 'The saved directory no longer exists. Returned to the download root.', readDirectoryFailed: 'Failed to read directory', noOptions: 'No options', select: 'Select', close: 'Close', progress: 'Progress', empty: 'Nothing here' },
}

for (const [locale, common] of Object.entries(extraCommonMessages)) {
  Object.assign(messages[locale].common, common)
}

export function normalizeLocale(value) {
  const locale = String(value || '').toLowerCase()
  if (locale.startsWith('zh-tw') || locale.startsWith('zh-hk') || locale.startsWith('zh-hant')) return 'zh-TW'
  if (locale.startsWith('ja')) return 'ja-JP'
  if (locale.startsWith('en')) return 'en-US'
  return 'zh-CN'
}

function detectLocale() {
  const saved = localStorage.getItem(LOCALE_STORAGE_KEY)
  if (saved) return normalizeLocale(saved)
  return normalizeLocale(navigator.languages?.[0] || navigator.language)
}

const initialLocale = detectLocale()

export const i18n = createI18n({
  legacy: false,
  globalInjection: true,
  locale: initialLocale,
  fallbackLocale: 'zh-CN',
  messages,
})

export function setLocale(value) {
  const locale = normalizeLocale(value)
  i18n.global.locale.value = locale
  localStorage.setItem(LOCALE_STORAGE_KEY, locale)
  document.documentElement.lang = locale
  return locale
}

document.documentElement.lang = initialLocale
